---
# (c) 2023 ViChanzo.  MIT License - see LICENSE file.
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
# Allow continer to lock memory
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: unless-stopped
    environment:
      - SERVER_NAME:kibana
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.12.0
    restart: unless-stopped
    command: logstash -f /config-dir/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
  
  metricbeat
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:8.7.0
    restart: unless-stopped
    command: -e
    environment:
      - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
      - "HOST_ELASTICSEARCH=elasticsearch:9200"
      - "HOST_KIBANA=kibana:5601"
    depends_on:
      - elasticsearch


volumes:
  elasticsearch-data:
    driver: local
